AllCops:
  Exclude:
    - 'app/controller/app/*.rb'
    - 'Rakefile'
    - 'Guardfile'
    - 'config.ru'
    - 'lib/**/*'
    - 'test/**/*'
    - 'config/**/*.rb'
    - 'config/*.rb'
    - 'db/**/*.rb'
    - 'rockets/**/*'
    - 'bin/*'