scss_files: 'app/assets/stylesheets/admin/**/*.scss'

ImportantRule:
  enabled: false

NestingDepth:
  enabled: false

SelectorDepth:
  enabled: false

SingleLinePerSelector:
  enabled: false

IdSelector:
  enabled: false
