---
- id: 1
  name: user_authenticate
  description: Function to block a view if the user is not authenticated
  position: 1
  deleted_at: 
  created_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-12-04 14:27:42.192901000 Z
    zone: &1 !ruby/object:ActiveSupport::TimeZone
      name: America/Caracas
    time: 2018-12-04 10:27:42.192901000 Z
  updated_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-12-04 14:27:42.192901000 Z
    zone: *1
    time: 2018-12-04 10:27:42.192901000 Z
