menu:
  keppler_frontend:
    name: Keppler Frontend
    current: ['']
    url_path: /admin/frontend/views
    icon: layers
    model: User
    # submenu:
    #   - option:
    #       name: name
    #       url_path: url_path
    #       current: ['current']
