---
- id: 3
  name: devise_login
  position: 1
  deleted_at: 
  created_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-09-20 14:29:57.838963000 Z
    zone: &1 !ruby/object:ActiveSupport::TimeZone
      name: America/Caracas
    time: 2018-09-20 10:29:57.838963000 Z
  updated_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-09-20 14:29:57.838963000 Z
    zone: *1
    time: 2018-09-20 10:29:57.838963000 Z
