---
- id: 1
  name: devise_login
  position: 1
  deleted_at: 
  created_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-11-13 12:30:35.557112000 Z
    zone: &1 !ruby/object:ActiveSupport::TimeZone
      name: America/Caracas
    time: 2018-11-13 08:30:35.557112000 Z
  updated_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-11-13 12:30:35.557112000 Z
    zone: *1
    time: 2018-11-13 08:30:35.557112000 Z
