modules:
  keppler_view:
    name: Frontend
    model: KepplerFrontendView
    actions: [
      'index'
    ]
    childrens:
      - keppler_frontend_themes:
          name: Themes
          model: KepplerFrontendTheme
          actions: [
            'index', 'create', 'update',
            'destroy'
          ]
      - keppler_frontend_callback_function:
          name: Multimedia
          model: KepplerFrontendCallbackMultimedia
          actions: [
            'index'
          ]
