modules:
 callback_functions:
    name: CallbackFunction
    actions: [
      'index', 'create', 'update',
      'destroy', 'download', 'upload',
      'clone'
    ]
  
#  themes:
#     name: Theme
#     actions: [
#       'index', 'create', 'update',
#       'destroy', 'download', 'upload',
#       'clone'
#     ]
#
#  views:
#     name: View
#     actions: [
#       'index', 'create', 'update',
#       'destroy', 'download', 'upload',
#       'clone'
#     ]
#

