modules:
  keppler_view:
    name: Views
    model: KepplerFrontendView
    actions: [
      'index', 'create', 'update',
      'destroy', 'download', 'upload',
      'clone', 'editor'
    ]
    childrens:
      - keppler_frontend_function:
          name: Functions
          model: KepplerFrontendFunction
          actions: [
            'index', 'create', 'update',
            'destroy', 'download', 'upload',
            'clone'
          ]
      - keppler_frontend_callback_function:
          name: Callback Functions
          model: KepplerFrontendCallbackFunction
          actions: [
            'index', 'create', 'update',
            'destroy', 'download', 'upload',
            'clone'
          ]
