modules:
  view:
    name: Views
    model: KepplerFrontendView
    actions: [
      'index', 'create', 'update',
      'destroy', 'download', 'upload',
      'clone', 'editor'
    ]
    childrens:
      # - parameters:
      #     name: KepplerFrontendParameter
      #     actions: [
      #       'index', 'create', 'update',
      #       'destroy', 'download', 'upload',
      #       'clone'
      #     ]
      - functions:
          name: Functions
          model: KepplerFrontendFunction
          actions: [
            'index', 'create', 'update',
            'destroy', 'download', 'upload',
            'clone'
          ]
      - callback_functions:
          name: Callback Functions
          model: KepplerFrontendCallbackFunction
          actions: [
            'index', 'create', 'update',
            'destroy', 'download', 'upload',
            'clone'
          ]
