modules:
 parameters:
    name: KepplerFrontendParameter
    actions: [
      'index', 'create', 'update',
      'destroy', 'download', 'upload',
      'clone'
    ]

 functions:
    name: KepplerFrontendFunction
    actions: [
      'index', 'create', 'update',
      'destroy', 'download', 'upload',
      'clone'
    ]

 callback_functions:
    name: KepplerFrontendCallbackFunction
    actions: [
      'index', 'create', 'update',
      'destroy', 'download', 'upload',
      'clone'
    ]
#  themes:
#     name: Theme
#     actions: [
#       'index', 'create', 'update',
#       'destroy', 'download', 'upload',
#       'clone'
#     ]
#
#  views:
#     name: View
#     actions: [
#       'index', 'create', 'update',
#       'destroy', 'download', 'upload',
#       'clone'
#     ]
#
