---
- id: 1
  name: keppler_default
  active: false
  position: 1
  deleted_at: 
  created_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2019-04-23 22:03:39.392687000 Z
    zone: &1 !ruby/object:ActiveSupport::TimeZone
      name: America/Caracas
    time: 2019-04-23 18:03:39.392687000 Z
  updated_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2019-04-25 15:31:04.062441000 Z
    zone: *1
    time: 2019-04-25 11:31:04.062441000 Z
- id: 5
  name: listashop
  active: true
  position: 2
  deleted_at: 
  created_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2019-04-25 15:30:57.372014000 Z
    zone: *1
    time: 2019-04-25 11:30:57.372014000 Z
  updated_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2019-04-25 15:31:04.104777000 Z
    zone: *1
    time: 2019-04-25 11:31:04.104777000 Z
