---
- id: 1
  name: keppler_default
  active: true
  position: 1
  deleted_at: 
  created_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-10-08 20:37:11.978683000 Z
    zone: &1 !ruby/object:ActiveSupport::TimeZone
      name: America/Caracas
    time: 2018-10-08 16:37:11.978683000 Z
  updated_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-10-26 19:45:09.652359000 Z
    zone: *1
    time: 2018-10-26 15:45:09.652359000 Z
