---
- id: 1
  name: keppler_default
  active: true
  position: 1
  deleted_at: 
  created_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-09-10 15:43:27.547190000 Z
    zone: &1 !ruby/object:ActiveSupport::TimeZone
      name: America/Caracas
    time: 2018-09-10 11:43:27.547190000 Z
  updated_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-09-19 16:09:10.900240000 Z
    zone: *1
    time: 2018-09-19 12:09:10.900240000 Z
