---
- id: 1
  name: keppler_default
  active: true
  position: 1
  deleted_at: 
  created_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2019-04-23 22:03:39.392687000 Z
    zone: &1 !ruby/object:ActiveSupport::TimeZone
      name: America/Caracas
    time: 2019-04-23 18:03:39.392687000 Z
  updated_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2019-04-26 13:46:09.834443000 Z
    zone: *1
    time: 2019-04-26 09:46:09.834443000 Z
