---
- id: 6
  name: Keppler Default
  active: true
  position: 1
  deleted_at: 
  created_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-07-30 20:09:27.198309000 Z
    zone: &1 !ruby/object:ActiveSupport::TimeZone
      name: America/Caracas
    time: 2018-07-30 16:09:27.198309000 Z
  updated_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-07-30 20:09:35.642122000 Z
    zone: *1
    time: 2018-07-30 16:09:35.642122000 Z
