---
- id: 1
  name: keppler_default
  active: true
  position: 1
  deleted_at: 
  created_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-08-09 19:21:26.059704000 Z
    zone: &1 !ruby/object:ActiveSupport::TimeZone
      name: America/Caracas
    time: 2018-08-09 15:21:26.059704000 Z
  updated_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-08-17 12:23:23.270360000 Z
    zone: *1
    time: 2018-08-17 08:23:23.270360000 Z
