---
- id: 1
  name: keppler
  url: "/keppler"
  method: GET
  active: true
  format_result: HTML
  position: 1
  deleted_at: 
  created_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-09-05 18:59:14.522840000 Z
    zone: &1 !ruby/object:ActiveSupport::TimeZone
      name: America/Caracas
    time: 2018-09-05 14:59:14.522840000 Z
  updated_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-09-05 18:59:14.522840000 Z
    zone: *1
    time: 2018-09-05 14:59:14.522840000 Z
- id: 13
  name: index
  url: "/"
  method: GET
  active: true
  format_result: HTML
  position: 2
  deleted_at: 
  created_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-09-21 15:07:49.440743000 Z
    zone: *1
    time: 2018-09-21 11:07:49.440743000 Z
  updated_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-09-21 15:07:49.440743000 Z
    zone: *1
    time: 2018-09-21 11:07:49.440743000 Z
