---
- id: 1
  name: keppler
  url: "/keppler"
  method: GET
  active: true
  format_result: HTML
  position: 1
  deleted_at: 
  created_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-10-01 12:55:32.156512000 Z
    zone: &1 !ruby/object:ActiveSupport::TimeZone
      name: America/Caracas
    time: 2018-10-01 08:55:32.156512000 Z
  updated_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-10-01 12:55:32.156512000 Z
    zone: *1
    time: 2018-10-01 08:55:32.156512000 Z
- id: 5
  name: index
  url: "/"
  method: GET
  active: true
  format_result: HTML
  position: 2
  deleted_at: 
  created_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-10-02 13:43:02.244500000 Z
    zone: *1
    time: 2018-10-02 09:43:02.244500000 Z
  updated_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-10-02 13:43:02.244500000 Z
    zone: *1
    time: 2018-10-02 09:43:02.244500000 Z
