---
- id: 65
  name: keppler
  url: "/keppler"
  method: GET
  active: true
  format_result: HTML
  position: 1
  deleted_at: 
  created_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-07-18 17:21:02.009921000 Z
    zone: &1 !ruby/object:ActiveSupport::TimeZone
      name: America/Caracas
    time: 2018-07-18 13:21:02.009921000 Z
  updated_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-07-19 18:24:47.474373000 Z
    zone: *1
    time: 2018-07-19 14:24:47.474373000 Z
- id: 90
  name: index
  url: "/"
  method: GET
  active: true
  format_result: HTML
  position: 2
  deleted_at: 
  created_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-07-19 20:03:32.109010000 Z
    zone: *1
    time: 2018-07-19 16:03:32.109010000 Z
  updated_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-07-19 20:03:32.109010000 Z
    zone: *1
    time: 2018-07-19 16:03:32.109010000 Z
- id: 91
  name: andres
  url: "/andres"
  method: GET
  active: true
  format_result: HTML
  position: 3
  deleted_at: 
  created_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-07-19 20:13:42.909435000 Z
    zone: *1
    time: 2018-07-19 16:13:42.909435000 Z
  updated_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-07-19 20:13:42.909435000 Z
    zone: *1
    time: 2018-07-19 16:13:42.909435000 Z
