---
- id: 1
  name: keppler
  url: "/keppler"
  method: GET
  active: true
  format_result: HTML
  position: 1
  deleted_at:
  created_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-08-30 18:53:43.223111000 Z
    zone: &1 !ruby/object:ActiveSupport::TimeZone
      name: America/Caracas
    time: 2018-08-30 14:53:43.223111000 Z
  updated_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-08-30 18:53:43.223111000 Z
    zone: *1
    time: 2018-08-30 14:53:43.223111000 Z
