---
- id: 1
  name: keppler
  url: "/keppler"
  method: GET
  active: true
  format_result: HTML
  position: 1
  deleted_at: 
  created_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-08-27 12:09:10.475042000 Z
    zone: &1 !ruby/object:ActiveSupport::TimeZone
      name: America/Caracas
    time: 2018-08-27 08:09:10.475042000 Z
  updated_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-08-27 12:09:10.475042000 Z
    zone: *1
    time: 2018-08-27 08:09:10.475042000 Z
- id: 3
  name: index
  url: "/"
  method: GET
  active: true
  format_result: HTML
  position: 2
  deleted_at: 
  created_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-08-27 14:23:05.008875000 Z
    zone: *1
    time: 2018-08-27 10:23:05.008875000 Z
  updated_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-08-27 14:23:05.008875000 Z
    zone: *1
    time: 2018-08-27 10:23:05.008875000 Z
