---
- id: 11
  name: keppler
  url: "/keppler"
  method: GET
  active: true
  format_result: HTML
  position: 1
  deleted_at: 
  created_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-08-10 19:03:03.744863000 Z
    zone: &1 !ruby/object:ActiveSupport::TimeZone
      name: America/Caracas
    time: 2018-08-10 15:03:03.744863000 Z
  updated_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-08-10 19:03:03.744863000 Z
    zone: *1
    time: 2018-08-10 15:03:03.744863000 Z
