---
- id: 52
  name: keppler
  url: "/keppler"
  method: ROOT
  active: true
  format_result: HTML
  position: 1
  deleted_at: 
  created_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-07-18 16:21:48.358723000 Z
    zone: &1 !ruby/object:ActiveSupport::TimeZone
      name: America/Caracas
    time: 2018-07-18 12:21:48.358723000 Z
  updated_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-07-18 16:21:48.358723000 Z
    zone: *1
    time: 2018-07-18 12:21:48.358723000 Z
