---
- id: 65
  name: keppler
  url: "/"
  method: GET
  active: true
  format_result: HTML
  position: 1
  deleted_at: 
  created_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-07-18 17:21:02.009921000 Z
    zone: &1 !ruby/object:ActiveSupport::TimeZone
      name: America/Caracas
    time: 2018-07-18 13:21:02.009921000 Z
  updated_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-07-18 17:38:17.238955000 Z
    zone: *1
    time: 2018-07-18 13:38:17.238955000 Z
