---
- id: 1
  key: titulo
  value: Titulo de valor
  language_id: 1
  position: 1
  deleted_at: 
  created_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-09-03 18:39:03.769335000 Z
    zone: &1 !ruby/object:ActiveSupport::TimeZone
      name: America/Caracas
    time: 2018-09-03 14:39:03.769335000 Z
  updated_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-09-03 18:39:03.769335000 Z
    zone: *1
    time: 2018-09-03 14:39:03.769335000 Z
