---
- id: 7
  key: firstname
  value: nombre
  language_id: 2
  position: 1
  deleted_at: 
  created_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-10-09 12:40:09.923293000 Z
    zone: &1 !ruby/object:ActiveSupport::TimeZone
      name: America/Caracas
    time: 2018-10-09 08:40:09.923293000 Z
  updated_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-10-09 12:40:09.923293000 Z
    zone: *1
    time: 2018-10-09 08:40:09.923293000 Z
- id: 8
  key: lastname
  value: apellido
  language_id: 2
  position: 2
  deleted_at: 
  created_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-10-09 12:40:09.935941000 Z
    zone: *1
    time: 2018-10-09 08:40:09.935941000 Z
  updated_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-10-09 12:40:09.935941000 Z
    zone: *1
    time: 2018-10-09 08:40:09.935941000 Z
- id: 9
  key: firstname
  value: firstname
  language_id: 3
  position: 3
  deleted_at: 
  created_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-10-09 12:48:30.832600000 Z
    zone: *1
    time: 2018-10-09 08:48:30.832600000 Z
  updated_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-10-09 12:48:30.832600000 Z
    zone: *1
    time: 2018-10-09 08:48:30.832600000 Z
- id: 10
  key: lastname
  value: lastname
  language_id: 3
  position: 4
  deleted_at: 
  created_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-10-09 12:48:30.840525000 Z
    zone: *1
    time: 2018-10-09 08:48:30.840525000 Z
  updated_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-10-09 12:48:30.840525000 Z
    zone: *1
    time: 2018-10-09 08:48:30.840525000 Z
