---
- id: 2
  name: es
  field_ids:
  - 7
  - 8
  position: 1
  deleted_at: 
  created_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-10-09 12:40:09.903170000 Z
    zone: &1 !ruby/object:ActiveSupport::TimeZone
      name: America/Caracas
    time: 2018-10-09 08:40:09.903170000 Z
  updated_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-10-09 12:48:48.875662000 Z
    zone: *1
    time: 2018-10-09 08:48:48.875662000 Z
  active: false
- id: 3
  name: en
  field_ids:
  - 9
  - 10
  position: 2
  deleted_at: 
  created_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-10-09 12:48:30.823789000 Z
    zone: *1
    time: 2018-10-09 08:48:30.823789000 Z
  updated_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-10-09 12:48:54.817421000 Z
    zone: *1
    time: 2018-10-09 08:48:54.817421000 Z
  active: true
