modules:
 fields:
    name: KepplerLanguagesField
    actions: [
      'index', 'create', 'update',
      'destroy', 'download', 'upload',
      'clone'
    ]

 languages:
    name: KepplerLanguagesLanguage
    actions: [
      'index', 'create', 'update',
      'destroy', 'download', 'upload',
      'clone'
    ]
