version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
        environment:
          RAILS_ENV: test
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          PGHOST: 127.0.0.1
          PGUSER: dev

      - image: circleci/postgres:9.4
        environment:
          POSTGRES_DB: keppler-test-dev
          POSTGRES_USER: dev
          POSTGRES_PASSWORD: dev

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      - run:
          name: database config
          command: |
            scp -r config/circleci/db_config.yml config/secrets.yml

      - run: bundle exec rake db:create RAILS_ENV=test
      - run: bundle exec rake db:migrate RAILS_ENV=test
      - run: bundle exec rake db:seed RAILS_ENV=test
      - run: bundle exec rubocop
      - run: gem install haml_lint
      - run: haml-lint app/views/admin
      - run: bundle exec rspec
