menu:
  keppler_nuevorocket:
    name: Keppler Nuevorocket
    current: ['']
    url_path: /
    icon: layers
    model: User
    submenu:
      - new:
          name: + Add new module
          url_path: url_path
          current: ['current']