---
- id: 8
  name: students
  position: 1
  deleted_at: 
  created_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-08-04 13:55:11.314464000 Z
    zone: &1 !ruby/object:ActiveSupport::TimeZone
      name: America/Caracas
    time: 2018-08-04 09:55:11.314464000 Z
  updated_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-08-04 13:55:11.314464000 Z
    zone: *1
    time: 2018-08-04 09:55:11.314464000 Z
