---
- id: 21
  name_field: photo
  format_field: string
  capsule_id: 13
  created_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-08-03 18:53:24.494403000 Z
    zone: &1 !ruby/object:ActiveSupport::TimeZone
      name: America/Caracas
    time: 2018-08-03 14:53:24.494403000 Z
  updated_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-08-03 18:53:24.494403000 Z
    zone: *1
    time: 2018-08-03 14:53:24.494403000 Z
- id: 22
  name_field: name
  format_field: string
  capsule_id: 13
  created_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-08-03 18:53:24.496717000 Z
    zone: *1
    time: 2018-08-03 14:53:24.496717000 Z
  updated_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-08-03 18:53:24.496717000 Z
    zone: *1
    time: 2018-08-03 14:53:24.496717000 Z
- id: 23
  name_field: description
  format_field: text
  capsule_id: 13
  created_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-08-03 18:53:24.498820000 Z
    zone: *1
    time: 2018-08-03 14:53:24.498820000 Z
  updated_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-08-03 18:53:24.498820000 Z
    zone: *1
    time: 2018-08-03 14:53:24.498820000 Z
