---
- id: 1
  name_field: name
  format_field: string
  capsule_id: 3
  created_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-08-06 20:21:59.266962000 Z
    zone: &1 !ruby/object:ActiveSupport::TimeZone
      name: America/Caracas
    time: 2018-08-06 16:21:59.266962000 Z
  updated_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-08-06 20:21:59.266962000 Z
    zone: *1
    time: 2018-08-06 16:21:59.266962000 Z
- id: 2
  name_field: description
  format_field: text
  capsule_id: 3
  created_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-08-06 20:21:59.276931000 Z
    zone: *1
    time: 2018-08-06 16:21:59.276931000 Z
  updated_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-08-06 20:21:59.276931000 Z
    zone: *1
    time: 2018-08-06 16:21:59.276931000 Z
- id: 3
  name_field: avatar
  format_field: string
  capsule_id: 3
  created_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-08-07 13:22:37.762746000 Z
    zone: *1
    time: 2018-08-07 09:22:37.762746000 Z
  updated_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-08-07 13:22:37.762746000 Z
    zone: *1
    time: 2018-08-07 09:22:37.762746000 Z
- id: 9
  name_field: age
  format_field: integer
  capsule_id: 3
  created_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-08-07 15:09:53.779775000 Z
    zone: *1
    time: 2018-08-07 11:09:53.779775000 Z
  updated_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-08-07 15:09:53.779775000 Z
    zone: *1
    time: 2018-08-07 11:09:53.779775000 Z
