---
- id: 7
  name: users
  position: 1
  deleted_at: 
  created_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-10-04 15:26:46.615576000 Z
    zone: &1 !ruby/object:ActiveSupport::TimeZone
      name: America/Caracas
    time: 2018-10-04 11:26:46.615576000 Z
  updated_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-10-04 15:26:46.615576000 Z
    zone: *1
    time: 2018-10-04 11:26:46.615576000 Z
- id: 8
  name: people
  position: 2
  deleted_at: 
  created_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-10-04 15:36:53.181869000 Z
    zone: *1
    time: 2018-10-04 11:36:53.181869000 Z
  updated_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-10-04 15:36:53.181869000 Z
    zone: *1
    time: 2018-10-04 11:36:53.181869000 Z
