---
- id: 21
  capsule_id: 3
  field: name
  validation: '10'
  name: validates_max_number
  created_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-08-07 19:24:12.177082000 Z
    zone: &1 !ruby/object:ActiveSupport::TimeZone
      name: America/Caracas
    time: 2018-08-07 15:24:12.177082000 Z
  updated_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-08-07 19:24:12.177082000 Z
    zone: *1
    time: 2018-08-07 15:24:12.177082000 Z
