menu:
  keppler_capsules:
    name: Keppler Capsules
    current: ['']
    icon: cursor
    model: KepplerCapsules::Capsule
    enviroment: development
    submenu:
      - option:
          name: add_capsule
          url_path: /admin/space/capsules
          current: ['current']
      # begin capusules generated (don't delete)
      - option:
          name: students
          url_path: /admin/space/students
          current: ['admin/students']
      # end capusules generated
