menu:
  keppler_capsules:
    name: Keppler Capsules
    current: ['']
    icon: cursor
    model: KepplerCapsules::Capsule
    enviroment: development
    submenu:
      - keppler_capsules_capsule:
          name: add_capsule
          url_path: /admin/space/capsules
          current: ['current']
          model: KepplerCapsules::Capsule
      # begin capusules generated (don't delete)
      - user:
          name: users
          url_path: /admin/space/users
          current: ['admin/users']
          model: KepplerCapsules::User
      - person:
          name: people
          url_path: /admin/space/people
          current: ['admin/people']
          model: KepplerCapsules::Person
      - dog:
          name: dogs
          url_path: /admin/space/dogs
          current: ['admin/dogs']
          model: KepplerCapsules::Dog
      # end capusules generated
