menu:
  keppler_capsules:
    name: Keppler Capsules
    current: ['']
    icon: cursor
    model: KepplerCapsules::Capsule
    enviroment: development
    submenu:
      - keppler_capsules_capsule:
          name: add_capsule
          url_path: /admin/space/capsules
          current: ['current']
          model: KepplerCapsules::Capsule
      # begin capsules generated (don't delete)
      # end capsules generated
