modules:
 students:
    name: Student
    actions: [
      'index', 'create', 'update',
      'destroy', 'download', 'upload',
      'clone'
    ]
  
 # capsules:
 #    name: Capsule
 #    actions: [
 #      'index', 'create', 'update',
 #      'destroy', 'download', 'upload',
 #      'clone'
 #    ]
 #
