modules:
 dog:
    name: Dog
    model: KepplerCapsulesDog
    actions: [
      'index', 'create', 'update',
      'destroy', 'download', 'upload',
      'clone'
    ]
  
 person:
    name: Person
    model: KepplerCapsulesPerson
    actions: [
      'index', 'create', 'update',
      'destroy', 'download', 'upload',
      'clone'
    ]
  
 user:
    name: User
    model: KepplerCapsulesUser
    actions: [
      'index', 'create', 'update',
      'destroy', 'download', 'upload',
      'clone'
    ]
  
  #
