modules:
  scripts:
    name: scripts
    actions:
      index: 'index'
      create: 'create'
      edit: 'edit'
      destroy: 'destroy'
      clone: 'clone'
      upload: 'upload'
      download: 'download'
  users:
    name: users
    actions:
      index: 'index'
      create: 'create'
      edit: 'edit'
      destroy: 'destroy'
      clone: 'clone'
      upload: 'upload'
      download: 'download'
    childrens:
      roles:
        name: roles
        actions:
          index: 'index'
          create: 'create'
          edit: 'edit'
          destroy: 'destroy'
          create_permissions: 'add permissions'
