modules:
  scripts:
    name: scripts
    actions: [
      'index', 'create', 'edit',
      'destroy', 'upload', 'download',
      'clone'
    ]
  users:
    name: users
    actions: [
      'index', 'create', 'edit',
      'destroy', 'upload', 'download',
      'clone'
    ]
    childrens:
      - roles:
        name: roles
        actions: [
          'index', 'create', 'edit',
          'destroy', 'add_permissions'
        ]
