modules:
  seo:
    name: Seo
    model: Seo
    actions: [
      'index', 'create', 'update',
      'destroy', 'download', 'upload',
      'clone'
    ]
  script:
    name: Scripts
    model: Script
    actions: [
      'index', 'create', 'update',
      'destroy', 'upload', 'download',
      'clone'
    ]
  meta_tag:
    name: MetaTags
    model: MetaTag
    actions: [
      'index', 'create', 'update',
      'destroy', 'upload', 'download',
      'clone'
    ]
  user:
    name: Users
    model: User
    actions: [
      'index', 'create', 'update',
      'destroy', 'download'
    ]
    childrens:
      - role:
          name: Roles
          model: Role
          actions: [
            'index', 'create', 'update',
            'destroy', 'download'
          ]
