modules:
  seos:
    name: Seo
    model: Seo
    actions: [
      'index', 'create', 'update',
      'destroy', 'download', 'upload',
      'clone'
    ]
  scripts:
    name: Scripts
    model: Script
    actions: [
      'index', 'create', 'update',
      'destroy', 'upload', 'download',
      'clone'
    ]
  meta_tags:
    name: MetaTags
    model: MetaTag
    actions: [
      'index', 'create', 'update',
      'destroy', 'upload', 'download',
      'clone'
    ]
  users:
    name: Users
    model: User
    actions: [
      'index', 'create', 'update',
      'destroy', 'download'
    ]
    childrens:
      - roles:
          name: Roles
          model: Role
          actions: [
            'index', 'create', 'update',
            'destroy', 'download'
          ]
