menu:
  keppler_luiz:
    name: Keppler Luiz
    current: ['/']
    url_path: /
    icon: layers
    model: User
    submenu:
      - new:
          # name: + Add new module
          # url_path: /url_path
          # current: ['/current_path']
          # enviroment: development
          # model: User