#= require jquery
#= require jquery-ui
#= require jquery_ujs
# require angular
#= require noty
#= require checklist-model
# require angular-local-storage
#= require nprogress
#= require nprogress-turbolinks
#= require ckeditor/init
#= require cocoon
#= require bootstrap-sprockets
#= require adminlte/app
#= require jquery.minicolors
#= require vue
#= require jquery.remotipart
#= require_tree .
